workspace/litellm-orchestrator:
- changed-files:
  - any-glob-to-any-file: ['workspaces/litellm-orchestrator/**']

workspace/src:
- changed-files:
  - any-glob-to-any-file: ['workspaces/src/**']

owner/area-maintainers:
- changed-files:
  - any-glob-to-any-file: ['workspaces/litellm-orchestrator/**', 'workspaces/src/**']