compressionLevel: mixed

enableGlobalCache: true

httpTimeout: 300000

nodeLinker: node-modules
nmMode: hardlinks-local

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.12.0.cjs

npmScopes:
  richardmcsong:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: 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
